packages:
  - "packages/*"
  - "apps/*"
  - "examples/*"
allowBuilds:
  esbuild: false
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
  - "@swc/core"
